# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('service_account.json', '.'),
        ('config.py', '.'),
        ('modules/*.py', 'modules'),
    ],
    hiddenimports=[
        'rapidfuzz',
        'rapidfuzz.fuzz',
        'rapidfuzz.process',
        'gspread',
        'google.oauth2.service_account',
        'google.auth',
        'google.auth.transport.requests',
        'openpyxl',
        'pandas',
        'pandas.io.formats.style',
        'requests',
        'cachetools',
        'pyasn1',
        'pyasn1_modules',
        'rsa',
        'urllib3',
        'charset_normalizer',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='핀시큐리티_공공입찰관리',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
